compile:
	g++ -o kruskal main.cpp UnionFind.cpp UnionFind.h Graph.cpp Graph.h Kruskal.cpp Kruskal.h

exec:
	./kruskal < kruskal.in

exec_our:
	./kruskal < kruskal.in > kruskal.out

test:
	./kruskal


